spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DjZhaopin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  mail:
    protocol: smtp
    host: smtp.sina.com
    default-encoding: UTF-8
    username: djzhaopine@sina.com
    password: 99b8829cfd32fb64
    test-connection: true
jwt:
  secret: djzhaopin123456
  expirationDateInMs: 86400000
  refreshExpirationDateInMs: 9000000
