spring:
  datasource:
    url: jdbc:postgresql://192.168.3.2:5432/djzhaopin
    username: dev
    password: dev1234
    driverClassName: org.postgresql.Driver
  redis:
    host: 192.168.3.2
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  mail:
    protocol: smtp
    host: smtp.sina.com
    default-encoding: UTF-8
    username: mrlinzc@sina.com # 此邮箱仅用于测试
    password: c0f6312871978056 # 此密码仅用于测试
    test-connection: true
jwt:
  secret: djzhaopin123456 # 此secret仅用于测试
  expirationDateInMs: 86400000
  refreshExpirationDateInMs: 9000000
